### ISSUE TITLE
Node.js version bug

### ISSUE THREAD

**Issue by markonije** [makeaixstudio/desktop#3] opened 2020-09-04 08:55 UTC
**Describe the bug**
Log that app makes if i start it from cmd

**To Reproduce**
1. Go to folder where app is installed (for me AppData/Local/aixstudiodesktop/app-2.0.1)
if i try outside of app-2.0.1 it does not say anynthing and nothing starts
2. Run aix studio.exe
![image](https://user-images.githubusercontent.com/63392259/92220904-f0c56a80-ee9c-11ea-84de-2089b57a89d3.png)

(I censored my windows username)

**Expected behavior**
I expect app to run

**Other info**
- OS Windows
- pre release

**Comment by cedkim** [comment] 2020-09-12 08:18
Hmm... thanks for reporting this. This seems to be the cause for some other issues and you've pointed me in the right direction. I'll have a look.

**Comment by cedkim** [comment] 2020-09-12 08:24
You seem to be using a terminal other than `cmd`. Would you be able to take another look?

**Comment by markonije** [comment] 2020-09-14 12:08
It is git bash or git cmd

**Comment by cedkim** [comment] 2020-09-15 07:46
Oh. Well I’ve tested that and it doesn’t open from there. Many programs have this issue so I’ll be closing this.

**Closed as completed by cedkim** 2020-09-15 07:46 UTC
Labels: bug
